version: "3.7"

services:
  app:
    build: .
    init: true
    # Markdownからpdfなどを作る際にディレクトリへの書き込み権限が無いので失敗する
    # rootで権限変更する
    # user: root
    ports:
      # サーバーモード起動時に使うポートを指定
      - "8080:8080"
      - "37717:37717"
      # - "127.0.0.1:8080:8080"
      # - "127.0.0.1:37717:37717"
    volumes:
      - .:/home/marp/app
